//
//  Generated file. Do not edit.
//
// This file is normally auto-generated by Flutter ("flutter pub get") based
// on the plugins listed in pubspec.yaml. It is included here as a placeholder
// so the Xcode project has a valid file reference. Running `flutter pub get`
// will regenerate it correctly with your actual plugins (dio, flutter_secure_storage,
// cached_network_image, etc. don't need iOS registration, but keep this file
// so Xcode doesn't show a missing-reference error).

import Foundation

public func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
}
